/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICorruptionsFont,
  ICorruptionsFontInterface,
} from "../ICorruptionsFont";

const _abi = [
  {
    inputs: [],
    name: "font",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICorruptionsFont__factory {
  static readonly abi = _abi;
  static createInterface(): ICorruptionsFontInterface {
    return new utils.Interface(_abi) as ICorruptionsFontInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICorruptionsFont {
    return new Contract(address, _abi, signerOrProvider) as ICorruptionsFont;
  }
}
