/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IGmRendererInterface,
  IGmRendererInterfaceInterface,
} from "../IGmRendererInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "__render",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IGmRendererInterface__factory {
  static readonly abi = _abi;
  static createInterface(): IGmRendererInterfaceInterface {
    return new utils.Interface(_abi) as IGmRendererInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGmRendererInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IGmRendererInterface;
  }
}
