/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface StringsLibInterface extends ethers.utils.Interface {
  functions: {
    "bytes3tohexstr(bytes3)": FunctionFragment;
    "svgBase64Data(bytes)": FunctionFragment;
    "uint24tohexstr(uint24)": FunctionFragment;
    "uint8tohexchar(uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "bytes3tohexstr",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "svgBase64Data",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uint24tohexstr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uint8tohexchar",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "bytes3tohexstr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "svgBase64Data",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uint24tohexstr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uint8tohexchar",
    data: BytesLike
  ): Result;

  events: {};
}

export class StringsLib extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StringsLibInterface;

  functions: {
    bytes3tohexstr(i: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    svgBase64Data(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    uint24tohexstr(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    uint8tohexchar(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;
  };

  bytes3tohexstr(i: BytesLike, overrides?: CallOverrides): Promise<string>;

  svgBase64Data(data: BytesLike, overrides?: CallOverrides): Promise<string>;

  uint24tohexstr(i: BigNumberish, overrides?: CallOverrides): Promise<string>;

  uint8tohexchar(i: BigNumberish, overrides?: CallOverrides): Promise<number>;

  callStatic: {
    bytes3tohexstr(i: BytesLike, overrides?: CallOverrides): Promise<string>;

    svgBase64Data(data: BytesLike, overrides?: CallOverrides): Promise<string>;

    uint24tohexstr(i: BigNumberish, overrides?: CallOverrides): Promise<string>;

    uint8tohexchar(i: BigNumberish, overrides?: CallOverrides): Promise<number>;
  };

  filters: {};

  estimateGas: {
    bytes3tohexstr(i: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    svgBase64Data(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    uint24tohexstr(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    uint8tohexchar(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bytes3tohexstr(
      i: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    svgBase64Data(
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    uint24tohexstr(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    uint8tohexchar(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
